INSERT INTO courses(title) VALUES("Bachelor of Arts in English"),
("Bachelor of Arts in Journalism"),
("Bachelor of Arts in Law Enforcement"),
("Bachelor of Arts in Legal Management"),
("Bachelor of Arts in Multimedia Arts"),
("Bachelor of Arts in Political Science"),
("Bachelor of Arts in Sociology"),
("Bachelor of Arts in Visual Communication"),
("Bachelor of Fine Arts"),
("Bachelor of Fine Arts (BFA)"),
("Bachelor of Science in Accounting and Financial Management"),
("Bachelor of Science in Actuarial Science"),
("Bachelor of Science in Agriculture"),
("Bachelor of Science in Agricultural Sciences"),
("Bachelor of Science in Biology"),
("Bachelor of Science in Business Administration"),
("Bachelor of Science in Business Administration (BSBA)"),
("Bachelor of Science in Business Administration (with a focus on Risk Management)"),
("Bachelor of Science in Chemical Engineering"),
("Bachelor of Science in Civil Engineering"),
("Bachelor of Science in Civil Engineering Technology"),
("Bachelor of Science in Communication"),
("Bachelor of Science in Construction Management"),
("Bachelor of Science in Criminology"),
("Bachelor of Science in Dental Technology"),
("Bachelor of Science in Electrical Engineering"),
("Bachelor of Science in Electronics and Communications Engineering"),
("Bachelor of Science in Electronics Engineering"),
("Bachelor of Science in Environmental Health"),
("Bachelor of Science in Environmental Science"),
("Bachelor of Science in Fisheries"),
("Bachelor of Science in Forensic Science"),
("Bachelor of Science in Geodetic Engineering"),
("Bachelor of Science in Health Informatics"),
("Bachelor of Science in Hospitality Management"),
("Bachelor of Science in Human Resource Management"),
("Bachelor of Science in Industrial Engineering"),
("Bachelor of Science in Industrial Relations"),
("Bachelor of Science in Industrial Technology"),
("Bachelor of Science in Insurance Management"),
("Bachelor of Science in Interior Design"),
("Bachelor of Science in Manufacturing Engineering"),
("Bachelor of Science in Marine Engineering"),
("Bachelor of Science in Marine Transportation"),
("Bachelor of Science in Mechanical Engineering"),
("Bachelor of Science in Microbiology"),
("Bachelor of Science in Mining Engineering"),
("Bachelor of Science in Multimedia Arts"),
("Bachelor of Science in Naval Architecture and Marine Engineering"),
("Bachelor of Science in Nutrition and Dietetics"),
("Bachelor of Science in Office Administration"),
("Bachelor of Science in Paralegal Studies"),
("Bachelor of Science in Petroleum Engineering"),
("Bachelor of Science in Performing Arts"),
("Bachelor of Science in Public Administration"),
("Bachelor of Science in Public Health"),
("Bachelor of Science in Public Safety"),
("Bachelor of Science in Psychology"),
("Bachelor of Science in Risk Management"),
("Bachelor of Science in Social Work"),
("Bachelor of Science in Tourism Management"),
("Bachelor of Science in Nursing"),
("Bachelor of Science in Radiologic Technology"),
("Bachelor of Science in Risk Management"),
("Bachelor of Science in Psychology"),
("Bachelor of Science in Marine Engineering"),
("Bachelor of Science in Mathematics"),
("Bachelor of Science in Office Administration"),
("Bachelor of Science in Business Administration"),
("Bachelor of Science in Law Enforcement"),
("Bachelor of Science in Management"),
("Bachelor of Science in Entrepreneurship"),
("Bachelor of Science in Aeronautics/Aircraft Maintenance"),
("Bachelor of Science in Computer Engineering"),
("Bachelor of Science in Architecture"),
("Bachelor of Science in Medical Technology"),
("Bachelor of Science in Forestry"),
("Bachelor of Science in Horticulture"),
("Bachelor of Science in Economics"),
("Bachelor of Science in Education"),
("Bachelor of Laws (LLB)"),
("Doctor of Medicine (MD)"),
("Doctor of Veterinary Medicine (DVM)"),
("Juris Doctor (J.D.)");