INSERT INTO schools (name) VALUES("ABE International Business College-Bacolod City"),
("ABE International Business College-Iloilo"),
("Aklan Catholic College"),
("Aklan Polytechnic College"),
("Aklan State University-Banga Campus"),
("Aklan State University-Ibajay Campus"),
("Aklan State University-Kalibo Campus"),
("Aklan State University-Makato"),
("Altavas College"),
("AMA Computer College-Bacolod"),
("AMA Computer College-Iloilo"),
("ACLC College of Iloilo"),
("ACSI College Iloilo"),
("Advance Central College"),
("Altavas College"),
("Balete Community College"),
("Baptist Missionary Association Bible College"),
("Bago City College"),
("Bacolod City College"),
("Binalbagan Catholic College"),
("Batan Integrated College of Technology"),
("Capiz State University-Burias Campus"),
("Capiz State University-Dumarao Campus"),
("Capiz State University-Dayao"),
("Capiz State University-Dumarao Campus"),
("Capiz State University-Ilog Campus"),
("Capiz State University-Main"),
("Capiz State University-Pilar Campus"),
("Capiz State University-Poblacion Mambusao"),
("Capiz State University-Pontevedra Campus"),
("Capiz State University-Sigma Campus"),
("Carlos Hilado Memorial State University-Alijis"),
("Carlos Hilado Memorial State University-Bacolod Campus"),
("Carlos Hilado Memorial State University-Main"),
("Carlos Hilado Memorial State University - College of Fisheries-Binalbagan"),
("Cabarrus Catholic College"),
("Cabalum Western College"),
("Central Philippines State University-Candoni"),
("Central Philippines State University-Cauayan Campus"),
("Central Philippines State University-Hinigaran Campus"),
("Central Philippines State University-Hinoba-an Campus"),
("Central Philippines State University-Ilog Campus"),
("Central Philippines State University-Main Campus"),
("Central Philippines State University-Moises Padilla Campus"),
("Central Philippines State University-Sipalay Campus"),
("Central Philippines State University-San Carlos Campus"),
("Central Philippines State University-Victorias City Campus"),
("Central Philippine Adventist College"),
("Central Philippine University"),
("Colegio de la Purisima Concepcion"),
("Colegio de San Jose-Jaro"),
("Colegio de Sta. Ana de Victorias"),
("Colegio del Sagrado Corazon de Jesus"),
("Colegio San Agustin-Bacolod"),
("College of Arts and Sciences of Asia and the Pacific-Bacolod City"),
("College of St. John-Roxas"),
("Convention Baptist Bible College"),
("CEDAR College"),
("Filamer Christian University"),
("Fellowship Baptist College of Kabankalan"),
("Garcia College of Technology"),
("Guimaras State College-Baterna Campus"),
("Guimaras State College-Main"),
("Guimaras State College-Mosqueda"),
("Hua Siong College of Iloilo"),
("Hercor College"),
("Iloilo City Community College"),
("Iloilo Doctors' College"),
("Iloilo Doctors' College of Medicine"),
("Iloilo Science and Technology University-Barotac Nuevo Campus"),
("Iloilo Science and Technology University-Dumangas Campus"),
("Iloilo Science and Technology University-Leon Campus"),
("Iloilo Science and Technology University-Miagao Campus"),
("Iloilo Science and Technology University-Main"),
("Iloilo Science and Technology University-Pototan Campus"),
("Iloilo State College of Fisheries-Barotac Nuevo Campus"),
("Iloilo State College of Fisheries-Dingle Campus"),
("Iloilo State College of Fisheries-Dumangas Campus"),
("Iloilo State College of Fisheries-Main"),
("Iloilo State College of Fisheries-San Enrique Campus"),
("Integrated Midwives Association of the Philippines Foundation School of Midwifery"),
("Interface Computer College-Iloilo"),
("John B. Lacson Colleges Foundation-Bacolod"),
("John B. Lacson Foundation Maritime University-Arevalo"),
("John B. Lacson Foundation Maritime University-Molo"),
("Kabankalan Catholic College"),
("La Carlota City College"),
("La Consolacion College-Bacolod"),
("La Consolacion College-Isabela"),
("Mater Dei College-Silay City"),
("Malay College"),
("Mount Carmel College"),
("Northern Iloilo State University-Ajuy Campus"),
("Northern Iloilo State University-Barotac Viejo Campus"),
("Northern Iloilo State University-Batad Campus"),
("Northern Iloilo State University-Concepcion Campus"),
("Northern Iloilo State University-Estancia Iloilo"),
("Northern Iloilo State University-Lemery Campus"),
("Northern Iloilo State University-Sara Campus"),
("Northern Negros State College of Science and Technology-Calatrava"),
("Northern Negros State College of Science and Technology-Escalante"),
("Northern Negros State College of Science and Technology-Main Campus"),
("Northwestern Visayan Colleges"),
("Pandan Bay Institute"),
("Philippine College of Business and Accountancy"),
("Philippine Normal University-Cadiz"),
("Riverside College"),
("St. Anthony College of Roxas City"),
("St. Gabriel College"),
("St. Paul University of Iloilo"),
("St. Therese-MTC Colleges-La Fiesta"),
("St. Therese-MTC Colleges-Magdalo"),
("St. Therese-MTC Colleges-Tigbauan"),
("St. Vincent College of Business and Accountancy"),
("St. Vincent College of Science and Technology"),
("St. Vincent Ferrer Seminary"),
("Sacred Heart Seminary (Bacolod) School"),
("Saint Anthony's College-Antique"),
("Saint John Mary Vianney Seminary College"),
("Santa Isabel College of Iloilo City"),
("Silay Institute"),
("Southland College of Kabankalan City"),
("STI College-Kalibo"),
("STI West Negros University"),
("Technological University of the Philippines-Visayas"),
("Tañon College"),
("University of Antique - Hamtic"),
("University of Antique - Main"),
("University of Antique - Tario Lim Antique School of Fisheries"),
("University of Iloilo"),
("University of Negros Occidental-Recoletos"),
("University of Perpetual Help System Laguna Pueblo de Panay Campus"),
("University of Saint La Salle"),
("University of San Agustin"),
("University of the Philippines Visayas"),
("VMA Global College"),
("Vicente A. Javier Memorial Community College"),
("West Visayas State University-Calinog Campus"),
("West Visayas State University-College of Agriculture and Forestry Lambunao"),
("West Visayas State University-Himamaylan Campus Extension"),
("West Visayas State University-Janiuay Campus"),
("West Visayas State University-Lambunao Campus"),
("West Visayas State University-Main"),
("West Visayas State University-Pototan Campus"),
("West Visayas State University-Pototan Campus"),
("West Visayas State University-Santa Barbara Campus");